package phone

var (
	ISO3166_Data []*PhoneData = []*PhoneData{
		&PhoneData{
			Alpha2:             "US",
			Alpha3:             "USA",
			CountryCode:        "1",
			CountryName:        "United States",
			MobileBeginsWith:   []string{"201", "202", "203", "205", "206", "207", "208", "209", "210", "212", "213", "214", "215", "216", "217", "218", "219", "224", "225", "227", "228", "229", "231", "234", "239", "240", "248", "251", "252", "253", "254", "256", "260", "262", "267", "269", "270", "272", "274", "276", "278", "281", "283", "301", "302", "303", "304", "305", "307", "308", "309", "310", "312", "313", "314", "315", "316", "317", "318", "319", "320", "321", "323", "325", "327", "330", "331", "334", "336", "337", "339", "341", "346", "347", "351", "352", "360", "361", "364", "369", "380", "385", "386", "401", "402", "404", "405", "406", "407", "408", "409", "410", "412", "413", "414", "415", "417", "419", "423", "424", "425", "430", "432", "434", "435", "440", "442", "443", "445", "447", "458", "464", "469", "470", "475", "478", "479", "480", "484", "501", "502", "503", "504", "505", "507", "508", "509", "510", "512", "513", "515", "516", "517", "518", "520", "530", "531", "534", "539", "540", "541", "551", "557", "559", "561", "562", "563", "564", "567", "570", "571", "573", "574", "575", "580", "582", "585", "586", "601", "602", "603", "605", "606", "607", "608", "609", "610", "612", "614", "615", "616", "617", "618", "619", "620", "623", "626", "627", "628", "630", "631", "636", "641", "646", "650", "651", "657", "659", "660", "661", "662", "667", "669", "678", "679", "681", "682", "689", "701", "702", "703", "704", "706", "707", "708", "712", "713", "714", "715", "716", "717", "718", "719", "720", "724", "725", "727", "730", "731", "732", "734", "737", "740", "747", "752", "754", "757", "760", "762", "763", "764", "765", "769", "770", "772", "773", "774", "775", "779", "781", "785", "786", "801", "802", "803", "804", "805", "806", "808", "810", "812", "813", "814", "815", "816", "817", "818", "828", "830", "831", "832", "835", "843", "845", "847", "848", "850", "856", "857", "858", "859", "860", "862", "863", "864", "865", "870", "872", "878", "901", "903", "904", "906", "907", "908", "909", "910", "912", "913", "914", "915", "916", "917", "918", "919", "920", "925", "927", "928", "929", "931", "935", "936", "937", "938", "940", "941", "947", "949", "951", "952", "954", "956", "957", "959", "970", "971", "972", "973", "975", "978", "979", "980", "984", "985", "989"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "AW",
			Alpha3:             "ABW",
			CountryCode:        "297",
			CountryName:        "Aruba",
			MobileBeginsWith:   []string{"5", "6", "7", "9"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "AF",
			Alpha3:             "AFG",
			CountryCode:        "93",
			CountryName:        "Afghanistan",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "AO",
			Alpha3:             "AGO",
			CountryCode:        "244",
			CountryName:        "Angola",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "AI",
			Alpha3:             "AIA",
			CountryCode:        "1",
			CountryName:        "Anguilla",
			MobileBeginsWith:   []string{"5", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "AX",
			Alpha3:             "ALA",
			CountryCode:        "358",
			CountryName:        "Åland Islands",
			MobileBeginsWith:   []string{"18"},
			PhoneNumberLengths: []int{6, 7, 8},
		},
		&PhoneData{
			Alpha2:             "AL",
			Alpha3:             "ALB",
			CountryCode:        "355",
			CountryName:        "Albania",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "AD",
			Alpha3:             "AND",
			CountryCode:        "376",
			CountryName:        "Andorra",
			MobileBeginsWith:   []string{"3", "4", "6"},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "AE",
			Alpha3:             "ARE",
			CountryCode:        "971",
			CountryName:        "United Arab Emirates",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "AR",
			Alpha3:             "ARG",
			CountryCode:        "54",
			CountryName:        "Argentina",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "AM",
			Alpha3:             "ARM",
			CountryCode:        "374",
			CountryName:        "Armenia",
			MobileBeginsWith:   []string{"5", "7", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "AS",
			Alpha3:             "ASM",
			CountryCode:        "1",
			CountryName:        "American Samoa",
			MobileBeginsWith:   []string{"733", "258"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "AG",
			Alpha3:             "ATG",
			CountryCode:        "1",
			CountryName:        "Antigua and Barbuda",
			MobileBeginsWith:   []string{"4", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "AU",
			Alpha3:             "AUS",
			CountryCode:        "61",
			CountryName:        "Australia",
			MobileBeginsWith:   []string{"4"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "AT",
			Alpha3:             "AUT",
			CountryCode:        "43",
			CountryName:        "Austria",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "AZ",
			Alpha3:             "AZE",
			CountryCode:        "994",
			CountryName:        "Azerbaijan",
			MobileBeginsWith:   []string{"4", "5", "6", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "BI",
			Alpha3:             "BDI",
			CountryCode:        "257",
			CountryName:        "Burundi",
			MobileBeginsWith:   []string{"7", "29"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BE",
			Alpha3:             "BEL",
			CountryCode:        "32",
			CountryName:        "Belgium",
			MobileBeginsWith:   []string{"4"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "BJ",
			Alpha3:             "BEN",
			CountryCode:        "229",
			CountryName:        "Benin",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BF",
			Alpha3:             "BFA",
			CountryCode:        "226",
			CountryName:        "Burkina Faso",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BD",
			Alpha3:             "BGD",
			CountryCode:        "880",
			CountryName:        "Bangladesh",
			MobileBeginsWith:   []string{"1"},
			PhoneNumberLengths: []int{8, 9, 10},
		},
		&PhoneData{
			Alpha2:             "BG",
			Alpha3:             "BGR",
			CountryCode:        "359",
			CountryName:        "Bulgaria",
			MobileBeginsWith:   []string{"87", "88", "89", "98", "99", "43"},
			PhoneNumberLengths: []int{8, 9},
		},
		&PhoneData{
			Alpha2:             "BH",
			Alpha3:             "BHR",
			CountryCode:        "973",
			CountryName:        "Bahrain",
			MobileBeginsWith:   []string{"3"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BS",
			Alpha3:             "BHS",
			CountryCode:        "1",
			CountryName:        "Bahamas",
			MobileBeginsWith:   []string{"3", "4", "5", "6", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "BA",
			Alpha3:             "BIH",
			CountryCode:        "387",
			CountryName:        "Bosnia and Herzegovina",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BY",
			Alpha3:             "BLR",
			CountryCode:        "375",
			CountryName:        "Belarus",
			MobileBeginsWith:   []string{"25", "29", "33", "44"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "BZ",
			Alpha3:             "BLZ",
			CountryCode:        "501",
			CountryName:        "Belize",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "BM",
			Alpha3:             "BMU",
			CountryCode:        "1",
			CountryName:        "Bermuda",
			MobileBeginsWith:   []string{"3", "5", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "BO",
			Alpha3:             "BOL",
			CountryCode:        "591",
			CountryName:        "Bolivia",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BR",
			Alpha3:             "BRA",
			CountryCode:        "55",
			CountryName:        "Brazil",
			MobileBeginsWith:   []string{"119", "129", "139", "149", "159", "169", "179", "189", "199", "219", "229", "249", "279", "289", "31", "32", "34", "38", "41", "43", "44", "45", "47", "48", "51", "53", "54", "55", "61", "62", "65", "67", "68", "69", "71", "73", "75", "77", "79", "81", "82", "83", "84", "85", "86", "91", "92", "95", "96", "98"},
			PhoneNumberLengths: []int{10, 11},
		},
		&PhoneData{
			Alpha2:             "BB",
			Alpha3:             "BRB",
			CountryCode:        "1",
			CountryName:        "Barbados",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "BN",
			Alpha3:             "BRN",
			CountryCode:        "673",
			CountryName:        "Brunei Darussalam",
			MobileBeginsWith:   []string{"7", "8"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "BT",
			Alpha3:             "BTN",
			CountryCode:        "975",
			CountryName:        "Bhutan",
			MobileBeginsWith:   []string{"17"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "BW",
			Alpha3:             "BWA",
			CountryCode:        "267",
			CountryName:        "Botswana",
			MobileBeginsWith:   []string{"71", "72", "73", "74", "75", "76"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CF",
			Alpha3:             "CAF",
			CountryCode:        "236",
			CountryName:        "Central African Republic",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CA",
			Alpha3:             "CAN",
			CountryCode:        "1",
			CountryName:        "Canada",
			MobileBeginsWith:   []string{"204", "226", "236", "249", "250", "289", "306", "343", "365", "403", "416", "418", "431", "437", "438", "450", "506", "514", "519", "579", "581", "587", "600", "604", "613", "639", "647", "705", "709", "778", "780", "807", "819", "867", "873", "902", "905"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "CH",
			Alpha3:             "CHE",
			CountryCode:        "41",
			CountryName:        "Switzerland",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "CL",
			Alpha3:             "CHL",
			CountryCode:        "56",
			CountryName:        "Chile",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "CN",
			Alpha3:             "CHN",
			CountryCode:        "86",
			CountryName:        "China",
			MobileBeginsWith:   []string{"13", "14", "15", "18"},
			PhoneNumberLengths: []int{11},
		},
		&PhoneData{
			Alpha2:             "CI",
			Alpha3:             "CIV",
			CountryCode:        "225",
			CountryName:        "Côte D'Ivoire",
			MobileBeginsWith:   []string{"0", "4", "5", "6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CM",
			Alpha3:             "CMR",
			CountryCode:        "237",
			CountryName:        "Cameroon",
			MobileBeginsWith:   []string{"7", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CD",
			Alpha3:             "COD",
			CountryCode:        "243",
			CountryName:        "Congo, The Democratic Republic Of The",
			MobileBeginsWith:   []string{"8", "9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "CG",
			Alpha3:             "COG",
			CountryCode:        "242",
			CountryName:        "Congo",
			MobileBeginsWith:   []string{"0"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "CK",
			Alpha3:             "COK",
			CountryCode:        "682",
			CountryName:        "Cook Islands",
			MobileBeginsWith:   []string{"5", "7"},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "CO",
			Alpha3:             "COL",
			CountryCode:        "57",
			CountryName:        "Colombia",
			MobileBeginsWith:   []string{"3"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "KM",
			Alpha3:             "COM",
			CountryCode:        "269",
			CountryName:        "Comoros",
			MobileBeginsWith:   []string{"3", "76"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "CV",
			Alpha3:             "CPV",
			CountryCode:        "238",
			CountryName:        "Cape Verde",
			MobileBeginsWith:   []string{"5", "9"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "CR",
			Alpha3:             "CRI",
			CountryCode:        "506",
			CountryName:        "Costa Rica",
			MobileBeginsWith:   []string{"5", "6", "7", "8"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CU",
			Alpha3:             "CUB",
			CountryCode:        "53",
			CountryName:        "Cuba",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "KY",
			Alpha3:             "CYM",
			CountryCode:        "1",
			CountryName:        "Cayman Islands",
			MobileBeginsWith:   []string{"345"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "CY",
			Alpha3:             "CYP",
			CountryCode:        "357",
			CountryName:        "Cyprus",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "CZ",
			Alpha3:             "CZE",
			CountryCode:        "420",
			CountryName:        "Czech Republic",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "DE",
			Alpha3:             "DEU",
			CountryCode:        "49",
			CountryName:        "Germany",
			MobileBeginsWith:   []string{"15", "16", "17"},
			PhoneNumberLengths: []int{10, 11},
		},
		&PhoneData{
			Alpha2:             "DJ",
			Alpha3:             "DJI",
			CountryCode:        "253",
			CountryName:        "Djibouti",
			MobileBeginsWith:   []string{"77"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "DM",
			Alpha3:             "DMA",
			CountryCode:        "1",
			CountryName:        "Dominica",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "DK",
			Alpha3:             "DNK",
			CountryCode:        "45",
			CountryName:        "Denmark",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "DO",
			Alpha3:             "DOM",
			CountryCode:        "1",
			CountryName:        "Dominican Republic",
			MobileBeginsWith:   []string{"809", "829", "849"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "DZ",
			Alpha3:             "DZA",
			CountryCode:        "213",
			CountryName:        "Algeria",
			MobileBeginsWith:   []string{"5", "6", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "EC",
			Alpha3:             "ECU",
			CountryCode:        "593",
			CountryName:        "Ecuador",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "EG",
			Alpha3:             "EGY",
			CountryCode:        "20",
			CountryName:        "Egypt",
			MobileBeginsWith:   []string{"1"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "ER",
			Alpha3:             "ERI",
			CountryCode:        "291",
			CountryName:        "Eritrea",
			MobileBeginsWith:   []string{"1", "7", "8"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "ES",
			Alpha3:             "ESP",
			CountryCode:        "34",
			CountryName:        "Spain",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "EE",
			Alpha3:             "EST",
			CountryCode:        "372",
			CountryName:        "Estonia",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "ET",
			Alpha3:             "ETH",
			CountryCode:        "251",
			CountryName:        "Ethiopia",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "FI",
			Alpha3:             "FIN",
			CountryCode:        "358",
			CountryName:        "Finland",
			MobileBeginsWith:   []string{"4", "5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "FJ",
			Alpha3:             "FJI",
			CountryCode:        "679",
			CountryName:        "Fiji",
			MobileBeginsWith:   []string{"7", "9"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "FK",
			Alpha3:             "FLK",
			CountryCode:        "500",
			CountryName:        "Falkland Islands (Malvinas)",
			MobileBeginsWith:   []string{"5", "6"},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "FR",
			Alpha3:             "FRA",
			CountryCode:        "33",
			CountryName:        "France",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "FO",
			Alpha3:             "FRO",
			CountryCode:        "298",
			CountryName:        "Faroe Islands",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "FM",
			Alpha3:             "FSM",
			CountryCode:        "691",
			CountryName:        "Micronesia, Federated States Of",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "GA",
			Alpha3:             "GAB",
			CountryCode:        "241",
			CountryName:        "Gabon",
			MobileBeginsWith:   []string{"05", "06", "07"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "GB",
			Alpha3:             "GBR",
			CountryCode:        "44",
			CountryName:        "United Kingdom",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "GE",
			Alpha3:             "GEO",
			CountryCode:        "995",
			CountryName:        "Georgia",
			MobileBeginsWith:   []string{"5", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "GH",
			Alpha3:             "GHA",
			CountryCode:        "233",
			CountryName:        "Ghana",
			MobileBeginsWith:   []string{"2", "5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "GI",
			Alpha3:             "GIB",
			CountryCode:        "350",
			CountryName:        "Gibraltar",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "GN",
			Alpha3:             "GIN",
			CountryCode:        "224",
			CountryName:        "Guinea",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "GP",
			Alpha3:             "GLP",
			CountryCode:        "590",
			CountryName:        "Guadeloupe",
			MobileBeginsWith:   []string{"690"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "GM",
			Alpha3:             "GMB",
			CountryCode:        "220",
			CountryName:        "Gambia",
			MobileBeginsWith:   []string{"7", "9"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "GW",
			Alpha3:             "GNB",
			CountryCode:        "245",
			CountryName:        "Guinea-Bissau",
			MobileBeginsWith:   []string{"5", "6", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "GQ",
			Alpha3:             "GNQ",
			CountryCode:        "240",
			CountryName:        "Equatorial Guinea",
			MobileBeginsWith:   []string{"222", "551"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "GR",
			Alpha3:             "GRC",
			CountryCode:        "30",
			CountryName:        "Greece",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "GD",
			Alpha3:             "GRD",
			CountryCode:        "1",
			CountryName:        "Grenada",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "GL",
			Alpha3:             "GRL",
			CountryCode:        "299",
			CountryName:        "Greenland",
			MobileBeginsWith:   []string{"4", "5"},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "GT",
			Alpha3:             "GTM",
			CountryCode:        "502",
			CountryName:        "Guatemala",
			MobileBeginsWith:   []string{"3", "4", "5"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "GF",
			Alpha3:             "GUF",
			CountryCode:        "594",
			CountryName:        "French Guiana",
			MobileBeginsWith:   []string{"694"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "GU",
			Alpha3:             "GUM",
			CountryCode:        "1",
			CountryName:        "Guam",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "GY",
			Alpha3:             "GUY",
			CountryCode:        "592",
			CountryName:        "Guyana",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "HK",
			Alpha3:             "HKG",
			CountryCode:        "852",
			CountryName:        "Hong Kong",
			MobileBeginsWith:   []string{"5", "6", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "HN",
			Alpha3:             "HND",
			CountryCode:        "504",
			CountryName:        "Honduras",
			MobileBeginsWith:   []string{"3", "7", "8", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "HR",
			Alpha3:             "HRV",
			CountryCode:        "385",
			CountryName:        "Croatia",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "HT",
			Alpha3:             "HTI",
			CountryCode:        "509",
			CountryName:        "Haiti",
			MobileBeginsWith:   []string{"3", "4"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "HU",
			Alpha3:             "HUN",
			CountryCode:        "36",
			CountryName:        "Hungary",
			MobileBeginsWith:   []string{"20", "30", "31", "70"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "ID",
			Alpha3:             "IDN",
			CountryCode:        "62",
			CountryName:        "Indonesia",
			MobileBeginsWith:   []string{"8"},
			PhoneNumberLengths: []int{9, 10, 11},
		},
		&PhoneData{
			Alpha2:             "IN",
			Alpha3:             "IND",
			CountryCode:        "91",
			CountryName:        "India",
			MobileBeginsWith:   []string{"7", "8", "9"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "IE",
			Alpha3:             "IRL",
			CountryCode:        "353",
			CountryName:        "Ireland",
			MobileBeginsWith:   []string{"82", "83", "84", "85", "86", "87", "88", "89"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "IR",
			Alpha3:             "IRN",
			CountryCode:        "98",
			CountryName:        "Iran, Islamic Republic Of",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "IQ",
			Alpha3:             "IRQ",
			CountryCode:        "964",
			CountryName:        "Iraq",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "IS",
			Alpha3:             "ISL",
			CountryCode:        "354",
			CountryName:        "Iceland",
			MobileBeginsWith:   []string{"6", "7", "8"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "IL",
			Alpha3:             "ISR",
			CountryCode:        "972",
			CountryName:        "Israel",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "IT",
			Alpha3:             "ITA",
			CountryCode:        "39",
			CountryName:        "Italy",
			MobileBeginsWith:   []string{"3"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "JM",
			Alpha3:             "JAM",
			CountryCode:        "1",
			CountryName:        "Jamaica",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "JO",
			Alpha3:             "JOR",
			CountryCode:        "962",
			CountryName:        "Jordan",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "JP",
			Alpha3:             "JPN",
			CountryCode:        "81",
			CountryName:        "Japan",
			MobileBeginsWith:   []string{"70", "80", "90"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "KZ",
			Alpha3:             "KAZ",
			CountryCode:        "7",
			CountryName:        "Kazakhstan",
			MobileBeginsWith:   []string{"70", "77"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "KE",
			Alpha3:             "KEN",
			CountryCode:        "254",
			CountryName:        "Kenya",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "KG",
			Alpha3:             "KGZ",
			CountryCode:        "996",
			CountryName:        "Kyrgyzstan",
			MobileBeginsWith:   []string{"5", "7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "KH",
			Alpha3:             "KHM",
			CountryCode:        "855",
			CountryName:        "Cambodia",
			MobileBeginsWith:   []string{"1", "6", "7", "8", "9"},
			PhoneNumberLengths: []int{8, 9},
		},
		&PhoneData{
			Alpha2:             "KI",
			Alpha3:             "KIR",
			CountryCode:        "686",
			CountryName:        "Kiribati",
			MobileBeginsWith:   []string{"9", "30"},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "KN",
			Alpha3:             "KNA",
			CountryCode:        "1",
			CountryName:        "Saint Kitts And Nevis",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "KR",
			Alpha3:             "KOR",
			CountryCode:        "82",
			CountryName:        "Korea, Republic of",
			MobileBeginsWith:   []string{"1"},
			PhoneNumberLengths: []int{9, 10},
		},
		&PhoneData{
			Alpha2:             "KW",
			Alpha3:             "KWT",
			CountryCode:        "965",
			CountryName:        "Kuwait",
			MobileBeginsWith:   []string{"5", "6", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "LA",
			Alpha3:             "LAO",
			CountryCode:        "856",
			CountryName:        "Lao People's Democratic Republic",
			MobileBeginsWith:   []string{"20"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "LB",
			Alpha3:             "LBN",
			CountryCode:        "961",
			CountryName:        "Lebanon",
			MobileBeginsWith:   []string{"3", "7"},
			PhoneNumberLengths: []int{7, 8},
		},
		&PhoneData{
			Alpha2:             "LR",
			Alpha3:             "LBR",
			CountryCode:        "231",
			CountryName:        "Liberia",
			MobileBeginsWith:   []string{"4", "5", "6", "7"},
			PhoneNumberLengths: []int{7, 8},
		},
		&PhoneData{
			Alpha2:             "LY",
			Alpha3:             "LBY",
			CountryCode:        "218",
			CountryName:        "Libyan Arab Jamahiriya",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "LC",
			Alpha3:             "LCA",
			CountryCode:        "1",
			CountryName:        "Saint Lucia",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "LI",
			Alpha3:             "LIE",
			CountryCode:        "423",
			CountryName:        "Liechtenstein",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "LK",
			Alpha3:             "LKA",
			CountryCode:        "94",
			CountryName:        "Sri Lanka",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "LS",
			Alpha3:             "LSO",
			CountryCode:        "266",
			CountryName:        "Lesotho",
			MobileBeginsWith:   []string{"5", "6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "LT",
			Alpha3:             "LTU",
			CountryCode:        "370",
			CountryName:        "Lithuania",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "LU",
			Alpha3:             "LUX",
			CountryCode:        "352",
			CountryName:        "Luxembourg",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "LV",
			Alpha3:             "LVA",
			CountryCode:        "371",
			CountryName:        "Latvia",
			MobileBeginsWith:   []string{"2"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MO",
			Alpha3:             "MAC",
			CountryCode:        "853",
			CountryName:        "Macao",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MA",
			Alpha3:             "MAR",
			CountryCode:        "212",
			CountryName:        "Morocco",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "MC",
			Alpha3:             "MCO",
			CountryCode:        "377",
			CountryName:        "Monaco",
			MobileBeginsWith:   []string{"4", "6"},
			PhoneNumberLengths: []int{8, 9},
		},
		&PhoneData{
			Alpha2:             "MD",
			Alpha3:             "MDA",
			CountryCode:        "373",
			CountryName:        "Moldova, Republic of",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MG",
			Alpha3:             "MDG",
			CountryCode:        "261",
			CountryName:        "Madagascar",
			MobileBeginsWith:   []string{"3"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "MV",
			Alpha3:             "MDV",
			CountryCode:        "960",
			CountryName:        "Maldives",
			MobileBeginsWith:   []string{"7", "9"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "MX",
			Alpha3:             "MEX",
			CountryCode:        "52",
			CountryName:        "Mexico",
			MobileBeginsWith:   []string{""},
			PhoneNumberLengths: []int{10, 11},
		},
		&PhoneData{
			Alpha2:             "MH",
			Alpha3:             "MHL",
			CountryCode:        "692",
			CountryName:        "Marshall Islands",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "MK",
			Alpha3:             "MKD",
			CountryCode:        "389",
			CountryName:        "Macedonia, the Former Yugoslav Republic Of",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "ML",
			Alpha3:             "MLI",
			CountryCode:        "223",
			CountryName:        "Mali",
			MobileBeginsWith:   []string{"6", "7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MT",
			Alpha3:             "MLT",
			CountryCode:        "356",
			CountryName:        "Malta",
			MobileBeginsWith:   []string{"79", "99"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MM",
			Alpha3:             "MMR",
			CountryCode:        "95",
			CountryName:        "Myanmar",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "ME",
			Alpha3:             "MNE",
			CountryCode:        "382",
			CountryName:        "Montenegro",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MN",
			Alpha3:             "MNG",
			CountryCode:        "976",
			CountryName:        "Mongolia",
			MobileBeginsWith:   []string{"5", "8", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MP",
			Alpha3:             "MNP",
			CountryCode:        "1",
			CountryName:        "Northern Mariana Islands",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "MZ",
			Alpha3:             "MOZ",
			CountryCode:        "258",
			CountryName:        "Mozambique",
			MobileBeginsWith:   []string{"8"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "MR",
			Alpha3:             "MRT",
			CountryCode:        "222",
			CountryName:        "Mauritania",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "MS",
			Alpha3:             "MSR",
			CountryCode:        "1",
			CountryName:        "Montserrat",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "MQ",
			Alpha3:             "MTQ",
			CountryCode:        "596",
			CountryName:        "Martinique",
			MobileBeginsWith:   []string{"696"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "MU",
			Alpha3:             "MUS",
			CountryCode:        "230",
			CountryName:        "Mauritius",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "MW",
			Alpha3:             "MWI",
			CountryCode:        "265",
			CountryName:        "Malawi",
			MobileBeginsWith:   []string{"77", "88", "99"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "MY",
			Alpha3:             "MYS",
			CountryCode:        "60",
			CountryName:        "Malaysia",
			MobileBeginsWith:   []string{"1"},
			PhoneNumberLengths: []int{9, 10},
		},
		&PhoneData{
			Alpha2:             "YT",
			Alpha3:             "MYT",
			CountryCode:        "269",
			CountryName:        "Mayotte",
			MobileBeginsWith:   []string{"639"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "NA",
			Alpha3:             "NAM",
			CountryCode:        "264",
			CountryName:        "Namibia",
			MobileBeginsWith:   []string{"60", "81", "82", "85"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "NC",
			Alpha3:             "NCL",
			CountryCode:        "687",
			CountryName:        "New Caledonia",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "NE",
			Alpha3:             "NER",
			CountryCode:        "227",
			CountryName:        "Niger",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "NF",
			Alpha3:             "NFK",
			CountryCode:        "672",
			CountryName:        "Norfolk Island",
			MobileBeginsWith:   []string{"5", "8"},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "NG",
			Alpha3:             "NGA",
			CountryCode:        "234",
			CountryName:        "Nigeria",
			MobileBeginsWith:   []string{"70", "80", "81"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "NI",
			Alpha3:             "NIC",
			CountryCode:        "505",
			CountryName:        "Nicaragua",
			MobileBeginsWith:   []string{"8"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "NU",
			Alpha3:             "NIU",
			CountryCode:        "683",
			CountryName:        "Niue",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{4},
		},
		&PhoneData{
			Alpha2:             "NL",
			Alpha3:             "NLD",
			CountryCode:        "31",
			CountryName:        "Netherlands",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "NO",
			Alpha3:             "NOR",
			CountryCode:        "47",
			CountryName:        "Norway",
			MobileBeginsWith:   []string{"4", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "NP",
			Alpha3:             "NPL",
			CountryCode:        "977",
			CountryName:        "Nepal",
			MobileBeginsWith:   []string{"97", "98"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "NR",
			Alpha3:             "NRU",
			CountryCode:        "674",
			CountryName:        "Nauru",
			MobileBeginsWith:   []string{"555"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "NZ",
			Alpha3:             "NZL",
			CountryCode:        "64",
			CountryName:        "New Zealand",
			MobileBeginsWith:   []string{"2"},
			PhoneNumberLengths: []int{8, 9, 10},
		},
		&PhoneData{
			Alpha2:             "OM",
			Alpha3:             "OMN",
			CountryCode:        "968",
			CountryName:        "Oman",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "PK",
			Alpha3:             "PAK",
			CountryCode:        "92",
			CountryName:        "Pakistan",
			MobileBeginsWith:   []string{"3"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "PA",
			Alpha3:             "PAN",
			CountryCode:        "507",
			CountryName:        "Panama",
			MobileBeginsWith:   []string{"5", "6"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "PE",
			Alpha3:             "PER",
			CountryCode:        "51",
			CountryName:        "Peru",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "PH",
			Alpha3:             "PHL",
			CountryCode:        "63",
			CountryName:        "Philippines",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "PW",
			Alpha3:             "PLW",
			CountryCode:        "680",
			CountryName:        "Palau",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "PG",
			Alpha3:             "PNG",
			CountryCode:        "675",
			CountryName:        "Papua New Guinea",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "PL",
			Alpha3:             "POL",
			CountryCode:        "48",
			CountryName:        "Poland",
			MobileBeginsWith:   []string{"5", "6", "7", "8"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "PR",
			Alpha3:             "PRI",
			CountryCode:        "1",
			CountryName:        "Puerto Rico",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "PT",
			Alpha3:             "PRT",
			CountryCode:        "351",
			CountryName:        "Portugal",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "PY",
			Alpha3:             "PRY",
			CountryCode:        "595",
			CountryName:        "Paraguay",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "PS",
			Alpha3:             "PSE",
			CountryCode:        "970",
			CountryName:        "Palestinian Territory, Occupied",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "PF",
			Alpha3:             "PYF",
			CountryCode:        "689",
			CountryName:        "French Polynesia",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "QA",
			Alpha3:             "QAT",
			CountryCode:        "974",
			CountryName:        "Qatar",
			MobileBeginsWith:   []string{"33", "55", "66", "77"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "RE",
			Alpha3:             "REU",
			CountryCode:        "262",
			CountryName:        "Réunion",
			MobileBeginsWith:   []string{"692", "693"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "RO",
			Alpha3:             "ROU",
			CountryCode:        "40",
			CountryName:        "Romania",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "RU",
			Alpha3:             "RUS",
			CountryCode:        "7",
			CountryName:        "Russian Federation",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "RW",
			Alpha3:             "RWA",
			CountryCode:        "250",
			CountryName:        "Rwanda",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SA",
			Alpha3:             "SAU",
			CountryCode:        "966",
			CountryName:        "Saudi Arabia",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SD",
			Alpha3:             "SDN",
			CountryCode:        "249",
			CountryName:        "Sudan",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SN",
			Alpha3:             "SEN",
			CountryCode:        "221",
			CountryName:        "Senegal",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SG",
			Alpha3:             "SGP",
			CountryCode:        "65",
			CountryName:        "Singapore",
			MobileBeginsWith:   []string{"8", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "SH",
			Alpha3:             "SHN",
			CountryCode:        "290",
			CountryName:        "Saint Helena",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{4},
		},
		&PhoneData{
			Alpha2:             "SJ",
			Alpha3:             "SJM",
			CountryCode:        "47",
			CountryName:        "Svalbard And Jan Mayen",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "SB",
			Alpha3:             "SLB",
			CountryCode:        "677",
			CountryName:        "Solomon Islands",
			MobileBeginsWith:   []string{"7", "8"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "SL",
			Alpha3:             "SLE",
			CountryCode:        "232",
			CountryName:        "Sierra Leone",
			MobileBeginsWith:   []string{"21", "25", "30", "33", "34", "40", "44", "50", "55", "76", "77", "78", "79", "88"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "SV",
			Alpha3:             "SLV",
			CountryCode:        "503",
			CountryName:        "El Salvador",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "SM",
			Alpha3:             "SMR",
			CountryCode:        "378",
			CountryName:        "San Marino",
			MobileBeginsWith:   []string{"3", "6"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "SO",
			Alpha3:             "SOM",
			CountryCode:        "252",
			CountryName:        "Somalia",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "PM",
			Alpha3:             "SPM",
			CountryCode:        "508",
			CountryName:        "Saint Pierre And Miquelon",
			MobileBeginsWith:   []string{"55"},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "RS",
			Alpha3:             "SRB",
			CountryCode:        "381",
			CountryName:        "Serbia",
			MobileBeginsWith:   []string{"6"},
			PhoneNumberLengths: []int{8, 9},
		},
		&PhoneData{
			Alpha2:             "ST",
			Alpha3:             "STP",
			CountryCode:        "239",
			CountryName:        "Sao Tome and Principe",
			MobileBeginsWith:   []string{"98", "99"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "SR",
			Alpha3:             "SUR",
			CountryCode:        "597",
			CountryName:        "Suriname",
			MobileBeginsWith:   []string{"6", "7", "8"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "SK",
			Alpha3:             "SVK",
			CountryCode:        "421",
			CountryName:        "Slovakia",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SI",
			Alpha3:             "SVN",
			CountryCode:        "386",
			CountryName:        "Slovenia",
			MobileBeginsWith:   []string{"3", "4", "5", "6", "7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "SE",
			Alpha3:             "SWE",
			CountryCode:        "46",
			CountryName:        "Sweden",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "SC",
			Alpha3:             "SYC",
			CountryCode:        "248",
			CountryName:        "Seychelles",
			MobileBeginsWith:   []string{"2"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "SY",
			Alpha3:             "SYR",
			CountryCode:        "963",
			CountryName:        "Syrian Arab Republic",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "TC",
			Alpha3:             "TCA",
			CountryCode:        "1",
			CountryName:        "Turks and Caicos Islands",
			MobileBeginsWith:   []string{"2", "3", "4"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "TD",
			Alpha3:             "TCD",
			CountryCode:        "235",
			CountryName:        "Chad",
			MobileBeginsWith:   []string{"6", "7", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "TG",
			Alpha3:             "TGO",
			CountryCode:        "228",
			CountryName:        "Togo",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "TH",
			Alpha3:             "THA",
			CountryCode:        "66",
			CountryName:        "Thailand",
			MobileBeginsWith:   []string{"8", "9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "TJ",
			Alpha3:             "TJK",
			CountryCode:        "992",
			CountryName:        "Tajikistan",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "TK",
			Alpha3:             "TKL",
			CountryCode:        "690",
			CountryName:        "Tokelau",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{4},
		},
		&PhoneData{
			Alpha2:             "TM",
			Alpha3:             "TKM",
			CountryCode:        "993",
			CountryName:        "Turkmenistan",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "TL",
			Alpha3:             "TLS",
			CountryCode:        "670",
			CountryName:        "Timor-Leste",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "TO",
			Alpha3:             "TON",
			CountryCode:        "676",
			CountryName:        "Tonga",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "TT",
			Alpha3:             "TTO",
			CountryCode:        "1",
			CountryName:        "Trinidad and Tobago",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "TN",
			Alpha3:             "TUN",
			CountryCode:        "216",
			CountryName:        "Tunisia",
			MobileBeginsWith:   []string{"2", "9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "TR",
			Alpha3:             "TUR",
			CountryCode:        "90",
			CountryName:        "Turkey",
			MobileBeginsWith:   []string{"5"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "TV",
			Alpha3:             "TUV",
			CountryCode:        "688",
			CountryName:        "Tuvalu",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{5},
		},
		&PhoneData{
			Alpha2:             "TW",
			Alpha3:             "TWN",
			CountryCode:        "886",
			CountryName:        "Taiwan, Province Of China",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "TZ",
			Alpha3:             "TZA",
			CountryCode:        "255",
			CountryName:        "Tanzania, United Republic of",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "UG",
			Alpha3:             "UGA",
			CountryCode:        "256",
			CountryName:        "Uganda",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "UA",
			Alpha3:             "UKR",
			CountryCode:        "380",
			CountryName:        "Ukraine",
			MobileBeginsWith:   []string{"39", "50", "63", "66", "67", "68", "9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "UY",
			Alpha3:             "URY",
			CountryCode:        "598",
			CountryName:        "Uruguay",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{8},
		},
		&PhoneData{
			Alpha2:             "UZ",
			Alpha3:             "UZB",
			CountryCode:        "998",
			CountryName:        "Uzbekistan",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "VC",
			Alpha3:             "VCT",
			CountryCode:        "1",
			CountryName:        "Saint Vincent And The Grenedines",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "VE",
			Alpha3:             "VEN",
			CountryCode:        "58",
			CountryName:        "Venezuela, Bolivarian Republic of",
			MobileBeginsWith:   []string{"4"},
			PhoneNumberLengths: []int{10},
		},
		&PhoneData{
			Alpha2:             "VG",
			Alpha3:             "VGB",
			CountryCode:        "1",
			CountryName:        "Virgin Islands, British",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "VI",
			Alpha3:             "VIR",
			CountryCode:        "1",
			CountryName:        "Virgin Islands, U.S.",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "VN",
			Alpha3:             "VNM",
			CountryCode:        "84",
			CountryName:        "Viet Nam",
			MobileBeginsWith:   []string{"9", "1"},
			PhoneNumberLengths: []int{9, 10},
		},
		&PhoneData{
			Alpha2:             "VU",
			Alpha3:             "VUT",
			CountryCode:        "678",
			CountryName:        "Vanuatu",
			MobileBeginsWith:   []string{"5", "7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "WF",
			Alpha3:             "WLF",
			CountryCode:        "681",
			CountryName:        "Wallis and Futuna",
			MobileBeginsWith:   []string{},
			PhoneNumberLengths: []int{6},
		},
		&PhoneData{
			Alpha2:             "WS",
			Alpha3:             "WSM",
			CountryCode:        "685",
			CountryName:        "Samoa",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{7},
		},
		&PhoneData{
			Alpha2:             "YE",
			Alpha3:             "YEM",
			CountryCode:        "967",
			CountryName:        "Yemen",
			MobileBeginsWith:   []string{"7"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "ZA",
			Alpha3:             "ZAF",
			CountryCode:        "27",
			CountryName:        "South Africa",
			MobileBeginsWith:   []string{"6", "7", "8"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "ZM",
			Alpha3:             "ZMB",
			CountryCode:        "260",
			CountryName:        "Zambia",
			MobileBeginsWith:   []string{"9"},
			PhoneNumberLengths: []int{9},
		},
		&PhoneData{
			Alpha2:             "ZW",
			Alpha3:             "ZWE",
			CountryCode:        "263",
			CountryName:        "Zimbabwe",
			MobileBeginsWith:   []string{"71", "73", "77"},
			PhoneNumberLengths: []int{9},
		},
	}
)
